AppBundle\Entity\Order:
  properties:
    name:

    - Length:
        min: 3
        max: 255
    phone:
    - NotBlank: ~
    - Length:
        min: 10
        max: 20
    comment:
    - Length:
        max: 255