AppBundle\Entity\Order:
  type: entity
  table: "`order`" # это слово зарезервировано MYSQL
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    phone:
      type: string
      length: 255
    comment:
      type: string
      length: 255
      nullable : true
    count:
      type: integer
      nullable: true
    is_sent:
      type: boolean
      options:
        default: 0
  manyToOne:
    product:
      targetEntity: AppBundle\Entity\Product
      joinColumn:
        name: product_id
        referencedColumnName: id

