AppBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        price:
            type: decimal
            scale: 2
        description:
            type: text
        category:
            type: integer
        consist:
            type: text
            nullable: true
        article:
            type: text
            nullable: true
    oneToMany:
        images:
            targetEntity: AppBundle\Entity\Image
            mappedBy: product