AppBundle\Entity\Stream:
  type: entity
  table: stream
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    streamId:
      type: string
      length: 255
  oneToOne:
    product:
      targetEntity: AppBundle\Entity\Product
      joinColumn:
        name: product_id
        referencedColumnName: id