assetic:
   debug:          '%kernel.debug%'
   use_controller: '%kernel.debug%'
   filters:
       scssphp:
           formatter: 'Leafo\ScssPhp\Formatter\Compressed'
       cssrewrite: ~
       jsqueeze: ~
