liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:

        # use the default cache configuration
        cache: ~

        # превьюшки для показа в карточках
        thumb_120:
            quality: 75
            filters:
                # create a thumbnail: set size to WxH and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [90, 120], mode: outbound }
        thumb_400:
            quality: 90
            filters:
                # create a thumbnail: set size to WxH and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [400, 400], mode: outbound }
