liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:

        # use the default cache configuration
        cache: ~

        # превьюшки для показа в карточках
        thumb_120:
            quality: 90
            filters:
                thumbnail: { size: [90, 120], mode: outbound }

        thumb_400:
            quality: 90
            filters:
                thumbnail: { size: [400, 400], mode: outbound }

        # надпись имеет пустое место внизу(2/3 картинки)
        thumb_200_wm_topped:
            quality: 90
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                watermark: {position: bottom, size: 0.5, image: ../web/assets/img/watermark/wm-base-topped.png}

        thumb_400_wm_topped:
            quality: 90
            filters:
                thumbnail: { size: [400, 400], mode: outbound }
                watermark: {position: bottom, size: 0.8, image: ../web/assets/img/watermark/wm-base-topped.png}

        # надпись по самому низу
        thumb_200_wm_base:
            quality: 90
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                watermark: {position: bottom, size: 0.5, image: ../web/assets/img/watermark/wm-base.png}