sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.product:
        class: Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product }
        public: true
    admin.image:
        class: Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Image }
        public: true
    admin.order:
        class: Admin\OrderAdmin
        arguments: [~, AppBundle\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Order }
        public: true
    file_manager:
        class: AppBundle\Service\FileManager
        arguments:
            $uploadDir: '%upload_directory%'
        public: true